### ISSUE TITLE
doc(blog): add `uses` page

### ISSUE THREAD

**Issue by heyfirst** [heyfirst/heyfirst.co#152]
### Todo:
- [x] Add `uses` page to heyfirst.co/uses (#156)
- [x] Add myself to https://uses.tech/ (https://github.com/wesbos/awesome-uses/pull/1376)
- [x] add title and SEO tag to `/uses`

### References
ref: https://uses.tech/
ref: https://garden.narze.live/Uses/
ref: https://wesbos.com/uses/
